### ISSUE TITLE
The NCTeX and NCTeXForm don't work

### ISSUE THREAD

**Issue by Albert9513** [NCAlgebra/NC#10]
![image](https://user-images.githubusercontent.com/97590797/149091891-ffc37276-672c-43d8-ba2b-39ff8a9afdda.png)

I have found out that the NCTeX and NCTeXForm do not work at all for me. I have followed the relevant instructions step by step in Chapter 8 "Pretty Output with Notebooks and", especially those in 8.2 Using NCTeX and 8.3 Using NCTeXForm, but nothing has done the trick.

As shown in the screen shot, NCTeXForm will return the very same instruction untouched and the NCTeX will pop up a DOS interface and keep it ever since. If the DOS interface is closed manually, the NCTeX will give $Failed.

The version of NCAlgebra I have installed is 5.0.4, and my Mathematica version is 12.3, my laptop runs on a Windows  10 system. I have been an active latex user for decades. The built-in TeXForm and "Copy as Latex" of MMA work normally as well as other add-ins or apps using Latex. As for NCAlgebra, the basic commands work well up to now as long as << NCAlgebra` is loaded after << NC`.

Is there any way to make the NCTeX and NCTeXForm work for me?  Thanks in advance!

**Comment by mcdeoliveira** [comment]
Debugging `NCTeX` can be a pain. Have you tried calling it with the `Verbose -> True` option? As in

    NCTeX[a ** b, Verbose -> True]

NCTeXForm is not working because it was not loaded. You have to load it before using it. You can use it with NCTeX but it is not required. The documentation is a bit outdated regarding it been loaded automatically. It is not. If you want to use it with NCTeX you can use the `TeXProcessor` option.

**Comment by mcdeoliveira** [comment]
Please email me directly if this is still an issue.

**Comment by Albert9513** [comment]
Thanks Mauricio, for your help. The bad news is that NCTeX still remains a lemon after calling it with Verbose -> True. However, the good news is that NCTeXForm  started to do the trick on my computer after it was manually loaded first. And the icing on the cake is, under most circumstances what I need is the latex code generated by NCTeXForm or TeXForm rather than a pdf picture displayed in my MMA notebook, as a result you do not have to debug NCTeX as long as NCTeXForm works.  Thanks !

**Comment by mcdeoliveira** [comment]
Happy to hear NCTexForm is serving you well. Setting up NCTeX can be hard but not impossible. Let me know if you need more help with that.
