### ISSUE TITLE
Error of "Incompatible elements in Join" occurs when loading <<NCAlgebra`

### ISSUE THREAD

**Issue by Albert9513** [NCAlgebra/NC#11]
![image](https://user-images.githubusercontent.com/97590797/149124428-876556b5-d81c-48c1-8781-c775ba03b1aa.png)

Error as shown above occurs each time when <<NCAlgebra` is loaded in MMA. Although there has not been any issue detected during the operation of the basic commands listed in Chapter 4 of the user's manual, I am still worried about the potential hidden mistakes this loading error can lead to in future computations. So I was wondering if there is any way to fix it, and what type of computations are prone to mistakes led by this loading error.

The version of my NCAlgebra is 5.0.4 while that of my MMA is 12.3. My laptop runs on a Win10 system.

Thanks in advance.

**Comment by mcdeoliveira** [comment]
I cannot reproduce the error you are reporting. I will try to get access to a Windows machine running this version of MMA to see if I can replicate it.

**Comment by mcdeoliveira** [comment]
Please email me directly if this is still an issue.

**Comment by JohnMarohn** [comment]
An issue for me also in NCAlgebra version 5.0.5.  Running macOS Version 12.1 and _Mathematica_ version 12.3.1.0.   Installed NCAlgebra via the Import[] mechanism.

**Comment by mcdeoliveira** [comment]
> An issue for me also in NCAlgebra version 5.0.5. Running macOS Version 12.1 and _Mathematica_ version 12.3.1.0. Installed NCAlgebra via the Import[] mechanism.

Try the version 5.0.6. Some issues with encodings in different environments were causing trauble.

**Comment by JohnMarohn** [comment]
Upgrading from NCAlgebra version 5.0.5 to version 5.0.5 (and from Mathematica version 12.3.1.0 to 13.0.0) solved the problem.  Thank you for the prompt response!  I am working on a package, built on NCAlgebra, that carries out unitary operator rotations in quantum mechanics.  Look for a public release at https://github.com/JohnMarohn/UniDyn around 03/21/22.

**Comment by mcdeoliveira** [comment]
Great. Beware that I am preparing a new release version (6.0.0), which should replace the current 5.0 series. There will be some breaking changes so you might want to take a look at that ahead of time to see if your package is going to be affected. Also let me know if there is any feature that you wished were available.
