### ISSUE TITLE
Constructing the abstract group multiplication table based on the defining relations or generating relations used to create the group elements.

### ISSUE THREAD

**Issue by hongyi-zhao** [NCAlgebra/NC#15]
The table 5.1 of the famous book ["The mathematical theory of symmetry in solids"][1] by C. J. Bradley & A. P.
Cracknell (called the BC book hereafter), defined the relations, classes, character tables, and matrix representatives for the abstract groups needed in the tabulation of the representations of the 230 space groups. [Here](https://book4you.org/book/2568515/afd9ea) you can find a PDF version of the book's most recent 2010 revised edition.

But unfortunately, the book does not provide the multiplication table corresponding to these abstract groups. So, I want to construct the abstract group multiplication table using the group elements symbolically with the help of Wolfram language. For your information, I listed the abstract group information of `G^3_8` given in the above book as an example:

![enter image description here][2]

And I also represented the corresponding result given by [the SpaceGroupIrep package](https://github.com/goodluck1982/SpaceGroupIrep), which can be seen as a Mathematica based database and group theory toolkit built on the above-mentioned book:

![enter image description here][3]

I want to know if the [`NC`](https://github.com/NCAlgebra/NC) package can help me solve this problem. Any hints will be highly appreciated. See [here](https://community.wolfram.com/groups/-/m/t/2512178?p_p_auth=Zmz9qjTU) for the related discussion.

Regards,
HZ

  [1]: https://www.amazon.com/Mathematical-Theory-Symmetry-Solids-Representation/dp/0199582580
  [2]: https://community.wolfram.com//c/portal/getImageAttachment?filename=Selection_171.png&userId=2470387
  [3]: https://community.wolfram.com//c/portal/getImageAttachment?filename=Selection_172.png&userId=2470387

**Comment by mcdeoliveira** [comment]
This is not really an issue with the software. You should try asking at stackexchange.
