### ISSUE TITLE
An incorrect result given in the `NCReplace` document.

### ISSUE THREAD

**Issue by hongyi-zhao** [NCAlgebra/NC#16]
In the document [`The fix is NCReplace`](https://github.com/NCAlgebra/NC/blob/master/DOCUMENTATION/MANUAL/Advanced.md#the-fix-is-ncreplace), the following example is shown:

> On the same vein, the following substitution rule
> 
> NCReplace[2 a**b + c, 2 a -> b]
> 
> will return 2 a**b + c intact since FullForm[2 a**b] is indeed
> 
> Times[2, NonCommutativeMuliply[a, b]]
> 
> which is not structurally related to FullForm[2 a], which is Times[2, a]. Of course, in this case a simple solution is to use the alternative rule:
> 
> NCReplace[2 a**b + c, a -> b / 2]
> 
> which results in b**b + c, as one might expect.

But according to my test, the above two methods give the exactly same results:

```mathematica
In[34]:= << NC`
<< NCAlgebra`

During evaluation of In[34]:= NC::Directory: You are using the version of NCAlgebra which is found in: "/home/werner/.Mathematica/Applications/NC/".

During evaluation of In[34]:= NCAlgebra::SmallCapSymbolsNonCommutative: All lower cap single letter symbols (e.g. a,b,c,...) were set as noncommutative.

In[44]:= NCReplace[2 a ** b + c, 2 a -> b]
NCReplace[2 a ** b + c, a -> b/2]

Out[44]= c + 2 a ** b

Out[45]= c + 2 a ** b
```

The results represented in the document are consistent with the behavior of `NCReplaceAll`:

```mathematica
In[46]:= NCReplaceAll[2 a ** b + c, 2 a -> b]
NCReplaceAll[2 a ** b + c, a -> b/2]

Out[46]= c + 2 a ** b

Out[47]= c + b ** b
```
Regards,
HZ

**Comment by mcdeoliveira** [comment]
That's correct! I will update it in the next version. Thanks a lot.

**Comment by mcdeoliveira** [comment]
It is now updated in the documentation of v6.0.0.
