### ISSUE TITLE
Trying to prepare a replacement rule incorrectly interchanges terms 

### ISSUE THREAD

**Issue by jibnew** [NCAlgebra/NC#19]
On 5.6 in Mathematica 11.0.1.0, Windows 11 I am trying to do
```
testrule = u[1,2]**iu[2,1]->1-u[1,1]**iu[1,1]
```
but the result is
```
iu[2, 1] u[1, 2] -> 1 - iu[1, 1] u[1, 1]
```
That is, `u` and `iu` get swapped for some reason.

**Comment by ievlevpn** [comment]
Did you set `iu` as non-commutative using `SetNonCommutative[iu]` before defining this rule? Only lower case _single_ letters are non-commutative by default.

**Comment by mcdeoliveira** [comment]
Most likely did not set iu to be NC as pointed out by ievlevpn.
