### ISSUE TITLE
Need a call of NCMatrixExpand

### ISSUE THREAD

**Issue by rebcabin** [NCAlgebra/NC#2]
In the introductory notebook 1_MostBasicCommands.nb, in the section "Matrices," there appears the product NCDot[m1, m2], with the output 

    {{a**d+b**e,2 a+3 b},{c**d+d**e,2 c+3 d}}

However, with a freshly booted kernel in MMA 11.1.1.0, I get the output

    {{a,b},{c,d}}**{{d,2},{e,3}}

I can get the documented output by writing 

    NCDot[m1, m2] // NCMatrixExpand

**Comment by mcdeoliveira** [comment]
What version NCAlgebra are you using? `NCDot` is a straightforward command and it simply evaluates the product. If you use:

    m1 = {{a, b}, {c, d}}
    m2 = {{d, 2}, {e, 3}}
    NCDot[m1, m2]

you should get

    {{a ** d + b ** e, 2 a + 3 b}, {c ** d + d ** e, 2 c + 3 d}}

If you issue

    m1 ** m2

you would get

    {{a,b},{c,d}}**{{d,2},{e,3}}

which you can later expand with `NCMatrixExpand`. Can you send me a small sample of your code from which I can reproduces the error?

**Comment by rebcabin** [comment]
ok, I am unable to reproduce the problem. Possibly, I had a contaminated kernel. My apologies.

**Comment by mcdeoliveira** [comment]
No worries!
