### ISSUE TITLE
NCCoefficientRules and NCCoefficientList not implemented correctly

### ISSUE THREAD

**Issue by LoaneShark** [NCAlgebra/NC#22]
The functions do not seem to exist despite being listed in the documentation, or at least are not recognized by the Mathematica engine (13.2) as defined functions after installing the most recent version of the Paclet (6.0.0). Happens both on browser and cloud versions.

Steps to reproduce: Open the "Most Basic Commands" living documentation notebook, and scroll down to the section pertaining to the `NCCoefficientRules` and `NCCoefficientList` examples. Run the cells defining the necessary variables, and then the relevant example function calls. The functions do not execute and the actual output does not match the expected output as presented by the documentation.

**Comment by mcdeoliveira** [comment]
Did you load NCPolyInterface as instructed right above the part you are referring to?

> NCAlgebra provides some commands for noncommutative polynomial manipulation that are similar to the native
> Mathematica (commutative) polynomial commands. Some of the next commands required the loading of the package
> 
>     << NCPolyInterface`
