### ISSUE TITLE
PacletInstall does not work (11.0.1.0)

### ISSUE THREAD

**Issue by jibnew** [NCAlgebra/NC#24]
In Mathematica 11.0.1.0, `PacletInstall["https://github.com/NCAlgebra/NC/blob/master/NCAlgebra-6.0.2.paclet?raw=true"];` returns `PacletInstall::notavail: No paclet named https://github.com/NCAlgebra/NC/blob/master/NCAlgebra-6.0.2.paclet?raw=true is available for download from any currently enabled paclet sites.`

**Comment by mcdeoliveira** [comment]
Many things can go wrong when it comes to network access. You can always download the paclet by typing the url and installing it from the local file in case all else fails. Please try that for the latest version.
