### ISSUE TITLE
Message thrown when importing NC with Needs

### ISSUE THREAD

**Issue by lucainnocenti** [NCAlgebra/NC#3]
When importing ``NC` `` using `Needs` the package throws the following message:

```
Needs::nocont: Context NC` was not created when Needs was evaluated.
```
The package is still loaded and works, but the message is quite annoying. Is it avoidable?

**Comment by mcdeoliveira** [comment]
Finally got time to make that happen in v5.0.6. It is now safe to import NC and NCAlgebra using Needs.
