### ISSUE TITLE
NCBX with commutative variables

### ISSUE THREAD

**Issue by esselltwo** [NCAlgebra/NC#4]
I was hoping to use this package to do some computations in a noncommutative algebra over the complex numbers. This involves polynomials in noncommuting variables with symbolic scalar coefficients and some relations on the noncommuting variables; as far as I can tell the standard way to deal with this/simplify expressions is to use Groebner bases.

However, those methods don't seem to work if there are any commuting variables involved. Is this supported at all? Would it be simple to add, or does it break the algorithm used in some fundamental way? I don't know much about Groebner bases so I'm not sure.

**Comment by mcdeoliveira** [comment]
The latest version of NCGB supports nc polynomials with commutative symbolic coefficients. This might be what you are looking for. The coefficients are however treated as if they were rationals, with the usual assumptions on invertibility in place wherever needed. It is limited to small problems though as the rational noncommutative coefficients quickly become quiet complex.
