### ISSUE TITLE
'Times' instead of '**' arise while using 'Series' of exponent of noncommuting operator

### ISSUE THREAD

**Issue by shamil777** [NCAlgebra/NC#7]
While I attempt to get `Series[ Exp[a x], {x,0,n} ]` where `a` is some non commuting entity I noticed that `Times` starts appearing instead of `NonCommutativeMultiply`. This behaviour arise 
when I set n to greater or equal to 3.

When I exdcute the following code you may notice some issues with the output:
![image](https://user-images.githubusercontent.com/23475057/75352003-105e5380-58ba-11ea-8c1f-e94a43e993ff.png)
As you can see at the screenshot I underlined the issue. Red underbrackets must contain `**` but for some reason it is converted to `Times`:
![image](https://user-images.githubusercontent.com/23475057/75352104-3e439800-58ba-11ea-9225-a3046d6f3064.png)

At the same time `res` works as intended. And expected behaviour of the `res2` is to coincide with `res`.

UPD: there is even simplier way to reproduce this behaviour:
![image](https://user-images.githubusercontent.com/23475057/75358710-6506cc00-58c4-11ea-80f2-1e1c0a17ee56.png)

Environment:
WM 11.1
Windows 10

version of the `NCAlgebra` is the latest at the moment: ffa53639c4d06b0b75310e59e8dc600f230932be

Link for the source code on my Google Drive: https://drive.google.com/file/d/1ZlI2XVTpFFSnqoT18D8fAvTp5c6LFF8N/view?usp=sharing

**Comment by mcdeoliveira** [comment]
That's is because of the way `Series` works, which is naturally using `Times` and not `**`. 
See also [the answer to this question](https://mathematica.stackexchange.com/questions/110658/how-to-write-the-taylor-expansion-of-the-sum-of-several-matrices/191397#191397) for a simple noncommutative version.
