### ISSUE TITLE
IterationLimit and RecursionLimit errors when loading package

### ISSUE THREAD

**Issue by gvercley** [NCAlgebra/NC#8]
When loading the package using 
<< NC`
<< NCAlgebra` several error messages are thrown and Mathematica seems tot take forever to finish the job.
The messages I get (before it turns off showing messages) are the following:

Message[$IterationLimit::itlim,4096]
<<NCSimplifyRational`
<<NCAlgebra`

$RecursionLimit::reclim2: Recursion depth of 1024 exceeded during evaluation of CommutativeQ[Pattern].

**Comment by mcdeoliveira** [comment]
Were you ever able to fix that?
